name: Build Performance

on:
  # Note! you can't safely use "pull_request_target" here
  # This workflow is mostly useful for "internal PRs"
  # External PRs won't be able to post a PR comment
  # See https://github.com/preactjs/compressed-size-action/issues/54
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/docs/**

jobs:
  build-size:
    name: Build Size Report
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build:website:en
          pattern: '{website/build/assets/js/main*js,website/build/assets/css/styles*css,website/.docusaurus/globalData.json,website/build/index.html,website/build/blog/index.html,website/build/blog/**/introducing-docusaurus/*,website/build/docs/index.html,website/build/docs/installation/index.html,website/build/tests/docs/index.html,website/build/tests/docs/standalone/index.html}'
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 30
          compression: none
  build-time:
    name: Build Time Perf
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - name: Installation
        run: yarn

      # Ensure build with a cold cache does not increase too much
      - name: Build (cold cache)
        run: yarn workspace website build --locale en
        timeout-minutes: 8

      # Ensure build with a warm cache does not increase too much
      - name: Build (warm cache)
        run: yarn workspace website build --locale en
        timeout-minutes: 2
    # TODO post a Github comment with build with perf warnings?
