name: Showcase Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - website/src/data/**

permissions:
  contents: read

jobs:
  validate-config:
    name: Validate Showcase Config
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v3
      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test website/src/data/__tests__/user.test.ts
