name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - yarn.lock
      - jest.config.mjs
      - packages/**
      - tsconfig.json

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.14', '16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website typecheck
      - name: Remove Theme Internal Re-export
        run: yarn workspace @docusaurus/theme-common removeThemeInternalReexport
      - name: Docusaurus Build
        run: yarn build:website:fast
