name: Swizzle Tests

on:
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Swizzle
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: ['eject', 'wrap']
        variant: ['js', 'ts']
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - name: Set up Node
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn

      # Swizzle all the theme components
      - name: Swizzle (${{matrix.action}} - ${{matrix.variant}})
        run: yarn workspace website test:swizzle:${{matrix.action}}:${{matrix.variant}}
      # Build swizzled site
      - name: Build website
        run: yarn build:website:fast
      # Ensure swizzled site still typechecks
      - name: TypeCheck website
        run: yarn workspace website typecheck
