name: Windows Tests

on:
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - package.json
      - yarn.lock
      - jest.config.mjs
      - packages/**
      - tsconfig.*.json
      - .github/workflows/tests-windows.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows-test:
    name: Windows Tests
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['20.0', '20', '22', '24', '25.1']
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn || yarn || yarn
      - name: Docusaurus Jest Tests
        run: yarn test
      - name: Create a deep path
        # https://github.com/facebook/docusaurus/pull/4899
        # https://github.com/facebook/docusaurus/issues/5793
        run: |
          mkdir -p "website/_dogfooding/_pages tests/deep-file-path-test/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar"
          cd "$_"
          echo "# hello" > test-file.md
      # Lightweight version of tests-swizzle.yml workflow, but for Windows
      - name: Swizzle Wrap TS
        run: yarn workspace website test:swizzle:wrap:ts
      - name: Docusaurus Build
        run: yarn build:website:fast
        env:
          DOCUSAURUS_PERF_LOGGER: 'true'

      - name: TypeCheck website
        # see https://github.com/facebook/docusaurus/pull/10486
        run: yarn workspace website typecheck
      - name: TypeCheck website - min version - v5.1
        run: |
          yarn add typescript@5.1.6 --exact -D -W --ignore-scripts

          # DocSearch@4/ai@5 doesn't support TS 5.1 (with skipLibCheck=false)
          jq '.resolutions."@docsearch/react" = "^3.9.0"' package.json > package.json.tmp && mv -Force package.json.tmp package.json
          yarn add @docsearch/react@^3.9.0 --exact -D -W --ignore-scripts

          yarn workspace website typecheck
      - name: TypeCheck website - max version - Latest
        # For latest TS there are often lib check errors, so we disable it
        # Details: https://github.com/facebook/docusaurus/pull/10486
        run: |
          yarn add typescript@latest --exact -D -W --ignore-scripts
          yarn workspace website typecheck --project tsconfig.skipLibCheck.json
