name: Windows Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/**

permissions:
  contents: read

jobs:
  windows-test:
    name: Windows Tests
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn || yarn || yarn # 3 attempts to avoid timeout errors...
      - name: Docusaurus Jest Tests
        run: yarn test
      - name: Create a deep path
        # https://github.com/facebook/docusaurus/pull/4899
        # https://github.com/facebook/docusaurus/issues/5793
        run: |
          mkdir -p "website/_dogfooding/_pages tests/deep-file-path-test/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar"
          cd "$_"
          echo "# hello" > test-file.md
      # Lightweight version of tests-swizzle.yml workflow, but for Windows
      - name: Swizzle Wrap TS
        run: yarn workspace website test:swizzle:wrap:ts
      - name: Docusaurus Build
        run: yarn build:website:fast
      - name: TypeCheck website
        run: yarn workspace website typecheck
